services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    volumes:
      - ./backend:/app
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "serve"]

networks:
  app-network:
    driver: bridge